//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMStudio.Applications.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMStudio.Applications.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application cannot create the solution &apos;{0}&apos;..
        /// </summary>
        internal static string CannotNewSolution {
            get {
                return ResourceManager.GetString("CannotNewSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application cannot open the solution &apos;{0}&apos;..
        /// </summary>
        internal static string CannotOpenSolution {
            get {
                return ResourceManager.GetString("CannotOpenSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application cannot save the file &apos;{0}&apos;..
        /// </summary>
        internal static string CannotSaveFile {
            get {
                return ResourceManager.GetString("CannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Data Documents (*.data).
        /// </summary>
        internal static string DataDocuments {
            get {
                return ResourceManager.GetString("DataDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFile.
        /// </summary>
        internal static string DefaultNewDocumentName {
            get {
                return ResourceManager.GetString("DefaultNewDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewSolution.
        /// </summary>
        internal static string DefaultNewSolutionName {
            get {
                return ResourceManager.GetString("DefaultNewSolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution path &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string NewSolutionPathInvalid {
            get {
                return ResourceManager.GetString("NewSolutionPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application so that the configuration changes take effect..
        /// </summary>
        internal static string RestartApplication {
            get {
                return ResourceManager.GetString("RestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution &apos;{0}&apos; has already existed..
        /// </summary>
        internal static string SolutionAlreadyExisted {
            get {
                return ResourceManager.GetString("SolutionAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution  &apos;{0}&apos; has already opened..
        /// </summary>
        internal static string SolutionAlreadyOpened {
            get {
                return ResourceManager.GetString("SolutionAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FMStuido Solution Documents (*.fmsln).
        /// </summary>
        internal static string SolutionDocuments {
            get {
                return ResourceManager.GetString("SolutionDocuments", resourceCulture);
            }
        }
    }
}
